/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edunova.zavrsni.view;

import edunova.zavrsni.controller.ObradaDjelatnik;
import edunova.zavrsni.model.Djelatnik;
import java.awt.event.KeyEvent;
import javax.persistence.NoResultException;
import javax.swing.JComponent;
import javax.swing.JOptionPane;

/**
 *
 * @author Skec
 */
public class Autorizacija extends javax.swing.JFrame {

    /**
     * Creates new form Autorizacija
     */
    public Autorizacija() {
        initComponents();
        setTitle(Aplikacija.NASLOV_APP);
        txtImeDjelatnika.setText("iva");
        pswSifraDjelatnika.setText("1234");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtImeDjelatnika = new javax.swing.JTextField();
        txtSifraDjelatnika = new javax.swing.JLabel();
        pswSifraDjelatnika = new javax.swing.JPasswordField();
        btnPrijava = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        jLabel1.setText("Ime djelatnika:");

        txtImeDjelatnika.setFont(new java.awt.Font("Calibri", 0, 15)); // NOI18N
        txtImeDjelatnika.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtImeDjelatnikaKeyReleased(evt);
            }
        });

        txtSifraDjelatnika.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        txtSifraDjelatnika.setText("Lozinka:");

        pswSifraDjelatnika.setFont(new java.awt.Font("Calibri", 0, 15)); // NOI18N
        pswSifraDjelatnika.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                pswSifraDjelatnikaKeyReleased(evt);
            }
        });

        btnPrijava.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        btnPrijava.setText("Prijava");
        btnPrijava.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrijavaActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon("D:\\Users\\Skec\\Desktop\\store-icon2.jpg")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btnPrijava, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 344, Short.MAX_VALUE)
                        .addComponent(pswSifraDjelatnika, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtImeDjelatnika, javax.swing.GroupLayout.Alignment.LEADING))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSifraDjelatnika, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtImeDjelatnika, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23)
                        .addComponent(txtSifraDjelatnika)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pswSifraDjelatnika, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(btnPrijava, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtImeDjelatnikaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtImeDjelatnikaKeyReleased
        if(evt.getKeyCode()==KeyEvent.VK_ENTER 
                && !txtImeDjelatnika.getText().isEmpty()){
           pswSifraDjelatnika.requestFocus();
        }
    }//GEN-LAST:event_txtImeDjelatnikaKeyReleased

    private void pswSifraDjelatnikaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pswSifraDjelatnikaKeyReleased
        if(evt.getKeyCode()==KeyEvent.VK_ENTER &&
                pswSifraDjelatnika.getPassword().length>0){
            prijaviSe();
        }
    }//GEN-LAST:event_pswSifraDjelatnikaKeyReleased

    private void btnPrijavaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrijavaActionPerformed
        prijaviSe();
    }//GEN-LAST:event_btnPrijavaActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPrijava;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPasswordField pswSifraDjelatnika;
    private javax.swing.JTextField txtImeDjelatnika;
    private javax.swing.JLabel txtSifraDjelatnika;
    // End of variables declaration//GEN-END:variables

    private void prijaviSe() {
        try{
            if(txtImeDjelatnika.getText().isEmpty()){
                obradiGresku(txtImeDjelatnika, "Obavezno ime!");
                return;
            }          

            if(pswSifraDjelatnika.getPassword().length==0){
                obradiGresku(pswSifraDjelatnika, "Obavezno šifra!");
                return;
            }

            ObradaDjelatnik oo = new ObradaDjelatnik();
            Djelatnik o = oo.autoriziraj(txtImeDjelatnika.getText(), pswSifraDjelatnika.getPassword());

            if(o==null){
                obradiGresku(pswSifraDjelatnika, "Ime i šifra ne odgovaraju");
                return;
            } 


            Aplikacija.djelatnik=o;
            new IzbornikPokusajTreci().setVisible(true);
            dispose();
        
        }catch(NoResultException e){
            obradiGresku(txtImeDjelatnika, "Nepostojeći djelatnik!");
        }
    }
    
    private void obradiGresku(JComponent komponenta, String poruka){
        komponenta.requestFocus();
        JOptionPane.showMessageDialog(rootPane, poruka);
    }
}
