/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edunova.zavrsni.view;

import edunova.zavrsni.controller.ObradaDjelatnik;
import edunova.zavrsni.model.Djelatnik;
import java.awt.event.KeyEvent;
import javax.swing.JComponent;
import javax.swing.JOptionPane;

/**
 *
 * @author Skec
 */
public class Autorizacija extends javax.swing.JFrame {

    /**
     * Creates new form Autorizacija
     */
    public Autorizacija() {
        initComponents();
        setTitle(Aplikacija.NASLOV_APP);
        txtImeDjelatnika.setText("iva");
        pswSifraDjelatnika.setText("1234");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtImeDjelatnika = new javax.swing.JTextField();
        txtSifraDjelatnika = new javax.swing.JLabel();
        pswSifraDjelatnika = new javax.swing.JPasswordField();
        btnPrijava = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel1.setText("Ime djelatnika:");

        txtImeDjelatnika.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtImeDjelatnikaKeyReleased(evt);
            }
        });

        txtSifraDjelatnika.setText("Šifra djelatnika:");

        pswSifraDjelatnika.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                pswSifraDjelatnikaKeyReleased(evt);
            }
        });

        btnPrijava.setText("Prijava");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(59, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtSifraDjelatnika)
                    .addComponent(txtImeDjelatnika)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pswSifraDjelatnika, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
                    .addComponent(btnPrijava, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(41, 41, 41))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtImeDjelatnika, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(txtSifraDjelatnika)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pswSifraDjelatnika, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnPrijava, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(76, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtImeDjelatnikaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtImeDjelatnikaKeyReleased
        if(evt.getKeyCode()==KeyEvent.VK_ENTER 
                && !txtImeDjelatnika.getText().isEmpty()){
           pswSifraDjelatnika.requestFocus();
        }
    }//GEN-LAST:event_txtImeDjelatnikaKeyReleased

    private void pswSifraDjelatnikaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pswSifraDjelatnikaKeyReleased
        if(evt.getKeyCode()==KeyEvent.VK_ENTER &&
                pswSifraDjelatnika.getPassword().length>0){
            prijaviSe();
        }
    }//GEN-LAST:event_pswSifraDjelatnikaKeyReleased

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPrijava;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPasswordField pswSifraDjelatnika;
    private javax.swing.JTextField txtImeDjelatnika;
    private javax.swing.JLabel txtSifraDjelatnika;
    // End of variables declaration//GEN-END:variables

    private void prijaviSe() {
        
        if(txtImeDjelatnika.getText().isEmpty()){
            obradiGresku(txtImeDjelatnika, "Obavezno ime!");
            return;
        }
        
//        try {
//            InternetAddress email=new InternetAddress(txtEmail.getText());
//            email.validate();
//        } catch (AddressException e) {
//            obradiGresku(txtEmail, "Email nije ispravan");
//            return;
//        }
        
      
        if(pswSifraDjelatnika.getPassword().length==0){
            obradiGresku(pswSifraDjelatnika, "Obavezno šifra!");
            return;
        }
        
        // znam kako je postavljen email i loznika
        ObradaDjelatnik oo = new ObradaDjelatnik();
        Djelatnik o = oo.autoriziraj(txtImeDjelatnika.getText(), pswSifraDjelatnika.getPassword());
        
        if(o==null){
            obradiGresku(pswSifraDjelatnika, "Ime i šifra ne odgovaraju");
            return;
        }
        
        
        Aplikacija.djelatnik=o;
        new Izbornik().setVisible(true);
        dispose();
    }
    
    private void obradiGresku(JComponent komponenta, String poruka){
        komponenta.requestFocus();
        JOptionPane.showMessageDialog(rootPane, poruka);
    }
}
