/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edunova.zavrsni.view;

import edunova.zavrsni.controller.ObradaDjelatnik;

/**
 *
 * @author Skec
 */
public class DjelatniciForma extends javax.swing.JFrame {

    private ObradaDjelatnik obradaDjelatnik;
    
    /**
     * Creates new form DjelatniciForma
     */
    public DjelatniciForma() {
        initComponents();
        obradaDjelatnik = new ObradaDjelatnik();
        setTitle(Aplikacija.NASLOV_APP + " | Djelatnik: " + Aplikacija.djelatnik.getIme());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        lstDjelatnici = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtImeDjelatika = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtPrezimeDjelatnika = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtOIB = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtJMBAG = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtStrucnaSprema = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        pswSifra = new javax.swing.JPasswordField();
        jLabel8 = new javax.swing.JLabel();
        pswSifraPotvrda = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jScrollPane1.setViewportView(lstDjelatnici);

        jLabel1.setText("Popis djelatnika:");

        jLabel2.setText("Ime djelatnika:");

        txtImeDjelatika.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtImeDjelatikaKeyReleased(evt);
            }
        });

        jLabel3.setText("Prezime kupca:");

        txtPrezimeDjelatnika.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPrezimeDjelatnikaKeyReleased(evt);
            }
        });

        jLabel4.setText("OIB:");

        txtOIB.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtOIBKeyReleased(evt);
            }
        });

        jLabel5.setText("JMBAG:");

        txtJMBAG.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtJMBAGKeyReleased(evt);
            }
        });

        jLabel6.setText("Stručna sprema:");

        txtStrucnaSprema.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtStrucnaSpremaKeyReleased(evt);
            }
        });

        jLabel7.setText("Šifra djelatnika:");

        jLabel8.setText("Potvrdi šifru djelatnika:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtImeDjelatika, javax.swing.GroupLayout.DEFAULT_SIZE, 269, Short.MAX_VALUE)
                            .addComponent(txtPrezimeDjelatnika, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtOIB, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtJMBAG, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtStrucnaSprema, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(pswSifra)
                            .addComponent(pswSifraPotvrda)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addComponent(jLabel1))
                .addGap(58, 58, 58))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtImeDjelatika, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPrezimeDjelatnika, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtOIB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtJMBAG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtStrucnaSprema, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pswSifra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pswSifraPotvrda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 82, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtImeDjelatikaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtImeDjelatikaKeyReleased
//        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
//            txtPrezimeDjelatnika.requestFocus();
//        }
    }//GEN-LAST:event_txtImeDjelatikaKeyReleased

    private void txtPrezimeDjelatnikaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPrezimeDjelatnikaKeyReleased
//        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
//            txtOIB.requestFocus();
//        }
    }//GEN-LAST:event_txtPrezimeDjelatnikaKeyReleased

    private void txtOIBKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtOIBKeyReleased
//        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
//            txtNazivFirme.requestFocus();
//        }
    }//GEN-LAST:event_txtOIBKeyReleased

    private void txtJMBAGKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtJMBAGKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJMBAGKeyReleased

    private void txtStrucnaSpremaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtStrucnaSpremaKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStrucnaSpremaKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> lstDjelatnici;
    private javax.swing.JPasswordField pswSifra;
    private javax.swing.JPasswordField pswSifraPotvrda;
    private javax.swing.JTextField txtImeDjelatika;
    private javax.swing.JTextField txtJMBAG;
    private javax.swing.JTextField txtOIB;
    private javax.swing.JTextField txtPrezimeDjelatnika;
    private javax.swing.JTextField txtStrucnaSprema;
    // End of variables declaration//GEN-END:variables
}
