/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edunova.zavrsni.view;

import edunova.zavrsni.controller.ObradaDjelatnik;
import edunova.zavrsni.model.Djelatnik;
import edunova.zavrsni.util.ZavrsniRadException;
import java.awt.event.KeyEvent;
import java.util.Arrays;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import org.mindrot.jbcrypt.BCrypt;

/**
 *
 * @author Skec
 */
public class DjelatniciForma extends javax.swing.JFrame {

    private ObradaDjelatnik obrada;
    
    /**
     * Creates new form DjelatniciForma
     */
    public DjelatniciForma() {
        initComponents();
        obrada = new ObradaDjelatnik();
        setTitle(Aplikacija.NASLOV_APP + " | Djelatnik: " + Aplikacija.djelatnik.getIme());
        ucitaj();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        lstDjelatnici = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtImeDjelatika = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtPrezimeDjelatnika = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtOIB = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtJMBAG = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtStrucnaSprema = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        pswSifra = new javax.swing.JPasswordField();
        jLabel8 = new javax.swing.JLabel();
        pswSifraPotvrda = new javax.swing.JPasswordField();
        btnOcistiPolja = new javax.swing.JButton();
        btnDodaj = new javax.swing.JButton();
        btnPromjeni = new javax.swing.JButton();
        btnObrisi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setType(java.awt.Window.Type.UTILITY);

        lstDjelatnici.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lstDjelatnici.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstDjelatniciValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(lstDjelatnici);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Popis djelatnika:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Ime djelatnika:");

        txtImeDjelatika.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtImeDjelatika.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtImeDjelatikaKeyReleased(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Prezime djelatnika:");

        txtPrezimeDjelatnika.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtPrezimeDjelatnika.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPrezimeDjelatnikaKeyReleased(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("OIB:");

        txtOIB.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtOIB.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtOIBKeyReleased(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("JMBAG:");

        txtJMBAG.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtJMBAG.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtJMBAGKeyReleased(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Stručna sprema:");

        txtStrucnaSprema.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtStrucnaSprema.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtStrucnaSpremaKeyReleased(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Lozinka djelatnika:");

        pswSifra.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        pswSifra.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                pswSifraKeyReleased(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Potvrdi lozinku djelatnika:");

        pswSifraPotvrda.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        btnOcistiPolja.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnOcistiPolja.setText("Očisti polja");
        btnOcistiPolja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOcistiPoljaActionPerformed(evt);
            }
        });

        btnDodaj.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnDodaj.setText("Dodaj");
        btnDodaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodajActionPerformed(evt);
            }
        });

        btnPromjeni.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnPromjeni.setText("Promjeni");
        btnPromjeni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPromjeniActionPerformed(evt);
            }
        });

        btnObrisi.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnObrisi.setText("Obriši");
        btnObrisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObrisiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtImeDjelatika, javax.swing.GroupLayout.DEFAULT_SIZE, 317, Short.MAX_VALUE)
                            .addComponent(txtPrezimeDjelatnika, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtOIB, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtJMBAG, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtStrucnaSprema, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(pswSifra)
                            .addComponent(btnOcistiPolja, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pswSifraPotvrda)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnDodaj, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnPromjeni, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnObrisi, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jLabel1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtImeDjelatika, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPrezimeDjelatnika, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtOIB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtJMBAG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtStrucnaSprema, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pswSifra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pswSifraPotvrda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnOcistiPolja)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnDodaj)
                            .addComponent(btnPromjeni)
                            .addComponent(btnObrisi)))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtImeDjelatikaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtImeDjelatikaKeyReleased
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            txtPrezimeDjelatnika.requestFocus();
        }
    }//GEN-LAST:event_txtImeDjelatikaKeyReleased

    private void txtPrezimeDjelatnikaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPrezimeDjelatnikaKeyReleased
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            txtOIB.requestFocus();
        }
    }//GEN-LAST:event_txtPrezimeDjelatnikaKeyReleased

    private void txtOIBKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtOIBKeyReleased
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            txtJMBAG.requestFocus();
        }
    }//GEN-LAST:event_txtOIBKeyReleased

    private void txtJMBAGKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtJMBAGKeyReleased
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            txtStrucnaSprema.requestFocus();
        }
    }//GEN-LAST:event_txtJMBAGKeyReleased

    private void txtStrucnaSpremaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtStrucnaSpremaKeyReleased
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            pswSifra.requestFocus();
        }
    }//GEN-LAST:event_txtStrucnaSpremaKeyReleased

    private void btnOcistiPoljaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOcistiPoljaActionPerformed
        pocisti();
        pswSifra.setEditable(true);
        pswSifraPotvrda.setEditable(true);
    }//GEN-LAST:event_btnOcistiPoljaActionPerformed

    private void btnDodajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodajActionPerformed

        obrada.setEntitet(new Djelatnik());
        postaviVrijednostiNaEntitet();

        try {
            obrada.create();
            pocisti();
            ucitaj();
        } catch (ZavrsniRadException ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getPoruka());
        }
        
        pswSifra.setEditable(true);
        pswSifraPotvrda.setEditable(true);
    }//GEN-LAST:event_btnDodajActionPerformed

    private void btnPromjeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPromjeniActionPerformed

        if (obrada.getEntitet() == null || obrada.getEntitet().getSifra() == null) {
            JOptionPane.showMessageDialog(rootPane, "Prvo odaberite djelatnika");
            return;
        }

        postaviVrijednostiNaEntitet();

        try {
            obrada.update();
            pocisti();
            ucitaj();
        } catch (ZavrsniRadException e) {
            JOptionPane.showMessageDialog(rootPane, e.getPoruka());
        }
        
        pswSifra.setEditable(true);
        pswSifraPotvrda.setEditable(true);
    }//GEN-LAST:event_btnPromjeniActionPerformed

    private void btnObrisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObrisiActionPerformed

        if (obrada.getEntitet() == null || obrada.getEntitet().getSifra() == null) {
            JOptionPane.showMessageDialog(rootPane, "Prvo odaberite djelatnika");
            return;
        }

        try {
            obrada.delete();
            pocisti();
            ucitaj();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Stavka se nalazi na računu - nemoguće obrisat!");
        }
        pswSifra.setEditable(true);
        pswSifraPotvrda.setEditable(true);
    }//GEN-LAST:event_btnObrisiActionPerformed

    private void pswSifraKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pswSifraKeyReleased
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            pswSifraPotvrda.requestFocus();
        }
    }//GEN-LAST:event_pswSifraKeyReleased

    private void lstDjelatniciValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstDjelatniciValueChanged
        
        if (evt.getValueIsAdjusting()) {
            return;
        }
       
        if (lstDjelatnici.getSelectedValue() == null) {
            pocisti();
            lstDjelatnici.clearSelection();
            return;
        }
        
        obrada.setEntitet(lstDjelatnici.getSelectedValue());

        txtImeDjelatika.setText(obrada.getEntitet().getIme());
        
        if (obrada.getEntitet().getPrezime() != null) {
            txtPrezimeDjelatnika.setText(obrada.getEntitet().getPrezime().toString());
        } else {
            txtPrezimeDjelatnika.setText("");
        }
        
        if (obrada.getEntitet().getOib() != null) {
            txtOIB.setText(obrada.getEntitet().getOib().toString());
        } else {
            txtOIB.setText("");
        }
        
        if (obrada.getEntitet().getJmbag()!= null) {
            txtJMBAG.setText(obrada.getEntitet().getJmbag().toString());
        } else {
            txtJMBAG.setText("");
        }
        
        if (obrada.getEntitet().getStrucnaSprema() != null) {
            txtStrucnaSprema.setText(obrada.getEntitet().getStrucnaSprema().toString());
        } else {
            txtStrucnaSprema.setText("");
        }
        
        pswSifra.setEditable(false);
        pswSifraPotvrda.setEditable(false);
    }//GEN-LAST:event_lstDjelatniciValueChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDodaj;
    private javax.swing.JButton btnObrisi;
    private javax.swing.JButton btnOcistiPolja;
    private javax.swing.JButton btnPromjeni;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<Djelatnik> lstDjelatnici;
    private javax.swing.JPasswordField pswSifra;
    private javax.swing.JPasswordField pswSifraPotvrda;
    private javax.swing.JTextField txtImeDjelatika;
    private javax.swing.JTextField txtJMBAG;
    private javax.swing.JTextField txtOIB;
    private javax.swing.JTextField txtPrezimeDjelatnika;
    private javax.swing.JTextField txtStrucnaSprema;
    // End of variables declaration//GEN-END:variables

    private void ucitaj() {

        DefaultListModel<Djelatnik> m = new DefaultListModel<>();
        m.addAll(obrada.getPodaci());
        lstDjelatnici.setModel(m);
    }

    private void pocisti() {
        
        txtImeDjelatika.setText("");
        txtPrezimeDjelatnika.setText("");
        txtJMBAG.setText("");
        txtOIB.setText("");
        txtStrucnaSprema.setText("");
        pswSifra.setText("");
        pswSifraPotvrda.setText("");
    }

    private void postaviVrijednostiNaEntitet() {
        
        var entitet = obrada.getEntitet();
        
        entitet.setIme(txtImeDjelatika.getText());
        
        try {
            entitet.setPrezime(txtPrezimeDjelatnika.getText());
        } catch (Exception e) {
            entitet.setPrezime("");
        }
        
        try {
            entitet.setOib(txtOIB.getText());
        } catch (Exception e) {
            entitet.setOib("");
        }
        
        try {
            entitet.setJmbag(txtJMBAG.getText());
        } catch (Exception e) {
            entitet.setJmbag("");
        }
        
        try {
            entitet.setStrucnaSprema(txtStrucnaSprema.getText());
        } catch (Exception e) {
            entitet.setStrucnaSprema("");
        }
        
        if(Arrays.equals(pswSifra.getPassword(), pswSifraPotvrda.getPassword())){
            try {
                char[] pass = pswSifra.getPassword();
                String s = new String(pass);
                obrada.getEntitet().setSifraDjelatnika(BCrypt.hashpw(s, BCrypt.gensalt()));
            } catch (Exception e) {
                JOptionPane.showMessageDialog(rootPane, "Problem s lozinkom!");
            }
        }else{
            JOptionPane.showMessageDialog(rootPane, "Nova lozinka se ne podudara!");
        }
    }
}
