/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edunova.zavrsni.view;

import edunova.zavrsni.controller.ObradaRacun;
import edunova.zavrsni.model.Racun;
import edunova.zavrsni.util.ZavrsniRadException;
import java.awt.event.KeyEvent;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author Skec
 */
public class IzbornikPokusajTreci extends javax.swing.JFrame {

    private ObradaRacun obradaRacun;
    
    /**
     * Creates new form IzbornikPokusajTreci
     */
    public IzbornikPokusajTreci() {
        initComponents();
        obradaRacun = new ObradaRacun();
        setTitle(Aplikacija.NASLOV_APP + " | Djelatnik: " + Aplikacija.djelatnik.getIme());
        new Vrijeme().start();
    }
    
    private class Vrijeme extends Thread{
        
        private SimpleDateFormat df = new SimpleDateFormat("dd. MMMM YYYY. HH:mm:ss");

        @Override
        public void run() {
            while (true) {                
                lblVrijeme.setText(df.format(new Date()));
                try {
                    Thread.sleep(1000);
                } catch (InterruptedException ex) {
                }
            }
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblProizvodi = new javax.swing.JLabel();
        lblKupci = new javax.swing.JLabel();
        btnKreirajNoviRacun = new javax.swing.JButton();
        lblRacuni = new javax.swing.JLabel();
        lblONama = new javax.swing.JLabel();
        lblPromjeniTrenutnogDjelatnika = new javax.swing.JLabel();
        jToolBar1 = new javax.swing.JToolBar();
        lblVrijeme = new javax.swing.JLabel();
        lblDjelatnici = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblProizvodi.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        lblProizvodi.setText("→ Proizvodi");
        lblProizvodi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblProizvodi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lblProizvodiMouseReleased(evt);
            }
        });

        lblKupci.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        lblKupci.setText("→ Kupci");
        lblKupci.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblKupci.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lblKupciMouseReleased(evt);
            }
        });

        btnKreirajNoviRacun.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        btnKreirajNoviRacun.setText("Kreiraj novi račun");
        btnKreirajNoviRacun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKreirajNoviRacunActionPerformed(evt);
            }
        });

        lblRacuni.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        lblRacuni.setText("→ Računi");
        lblRacuni.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblRacuni.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lblRacuniMouseReleased(evt);
            }
        });

        lblONama.setFont(new java.awt.Font("Calibri", 0, 20)); // NOI18N
        lblONama.setText("O nama ←");
        lblONama.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblONama.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lblONamaMouseReleased(evt);
            }
        });

        lblPromjeniTrenutnogDjelatnika.setFont(new java.awt.Font("Calibri", 0, 20)); // NOI18N
        lblPromjeniTrenutnogDjelatnika.setText("Promjeni trenutnog djelatnika ←");
        lblPromjeniTrenutnogDjelatnika.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblPromjeniTrenutnogDjelatnika.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lblPromjeniTrenutnogDjelatnikaMouseReleased(evt);
            }
        });

        jToolBar1.setRollover(true);

        lblVrijeme.setText("vrijeme");
        jToolBar1.add(lblVrijeme);

        lblDjelatnici.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        lblDjelatnici.setText("→ Djelatnici");
        lblDjelatnici.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblDjelatnici.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lblDjelatniciMouseReleased(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Calibri", 0, 20)); // NOI18N
        jLabel1.setText("Promjeni lozinku trenutnog djelatnika ←");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel1MouseReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblDjelatnici, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnKreirajNoviRacun, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblRacuni, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblONama))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(lblKupci, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(156, 156, 156)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblProizvodi, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblPromjeniTrenutnogDjelatnika)))
                        .addContainerGap(45, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProizvodi, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPromjeniTrenutnogDjelatnika, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblKupci, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRacuni, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblONama, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblDjelatnici, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(btnKreirajNoviRacun)
                .addGap(38, 38, 38))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblProizvodiMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblProizvodiMouseReleased
        new ProizvodiForma().setVisible(true);
    }//GEN-LAST:event_lblProizvodiMouseReleased

    private void lblKupciMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblKupciMouseReleased
        new KupciForma().setVisible(true);
    }//GEN-LAST:event_lblKupciMouseReleased

    private void btnKreirajNoviRacunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKreirajNoviRacunActionPerformed
        new NoviRacunForma().setVisible(true);
    }//GEN-LAST:event_btnKreirajNoviRacunActionPerformed

    private void lblRacuniMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRacuniMouseReleased
        new RacuniForma().setVisible(true);
    }//GEN-LAST:event_lblRacuniMouseReleased

    private void lblONamaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblONamaMouseReleased
        JOptionPane.showMessageDialog(rootPane, "© " + Aplikacija.NASLOV_APP + "\n programmed by: Iva Ivezić" );
    }//GEN-LAST:event_lblONamaMouseReleased

    private void lblPromjeniTrenutnogDjelatnikaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPromjeniTrenutnogDjelatnikaMouseReleased
        
        int selectedOption = JOptionPane.showConfirmDialog(null,
            "Želiš li promjeniti djelatnika?", "FrameToClose", JOptionPane.YES_NO_OPTION);
        if (selectedOption == JOptionPane.YES_OPTION) {
            setVisible(false);
            dispose();
            new SplashScreen().setVisible(true);
        } else {
            setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        }
    }//GEN-LAST:event_lblPromjeniTrenutnogDjelatnikaMouseReleased

    private void lblDjelatniciMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDjelatniciMouseReleased
        new DjelatniciForma().setVisible(true);
    }//GEN-LAST:event_lblDjelatniciMouseReleased

    private void jLabel1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseReleased
        new PromjeniLozinkuDjelatnikaForma().setVisible(true);
    }//GEN-LAST:event_jLabel1MouseReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKreirajNoviRacun;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel lblDjelatnici;
    private javax.swing.JLabel lblKupci;
    private javax.swing.JLabel lblONama;
    private javax.swing.JLabel lblProizvodi;
    private javax.swing.JLabel lblPromjeniTrenutnogDjelatnika;
    private javax.swing.JLabel lblRacuni;
    private javax.swing.JLabel lblVrijeme;
    // End of variables declaration//GEN-END:variables

  
}
