/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edunova.zavrsni.view;

import edunova.zavrsni.controller.ObradaProizvod;
import edunova.zavrsni.model.Proizvod;
import edunova.zavrsni.util.ZavrsniRadException;
import java.awt.event.KeyEvent;
import java.math.BigDecimal;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Skec
 */
public class ProizvodiForma extends javax.swing.JFrame {

    private ObradaProizvod obrada;
    
    /**
     * Creates new form ProizvodiForma
     */
    public ProizvodiForma() {
        
        initComponents();
        obrada = new ObradaProizvod();
        setTitle(Aplikacija.NASLOV_APP + " | Djelatnik: " + Aplikacija.djelatnik.getIme());
        ucitaj();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        lstProizvodi = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        txtNazivProizvoda = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtProizvodac = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtOpis = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtCijena = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtKolicinaNaStanju = new javax.swing.JTextField();
        btnDodaj = new javax.swing.JButton();
        btnPromjeni = new javax.swing.JButton();
        btnObrisi = new javax.swing.JButton();
        btnOcistiPolja = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setType(java.awt.Window.Type.UTILITY);

        lstProizvodi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lstProizvodi.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstProizvodiValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(lstProizvodi);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Naziv proizvoda:");

        txtNazivProizvoda.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtNazivProizvoda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNazivProizvodaKeyReleased(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Proizvođač:");

        txtProizvodac.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtProizvodac.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtProizvodacKeyReleased(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Opis:");

        txtOpis.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtOpis.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtOpisKeyReleased(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Cijena:");

        txtCijena.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtCijena.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCijenaKeyReleased(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Količina na stanju:");

        txtKolicinaNaStanju.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        btnDodaj.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnDodaj.setText("Dodaj");
        btnDodaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodajActionPerformed(evt);
            }
        });

        btnPromjeni.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnPromjeni.setText("Promjeni");
        btnPromjeni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPromjeniActionPerformed(evt);
            }
        });

        btnObrisi.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnObrisi.setText("Obriši");
        btnObrisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObrisiActionPerformed(evt);
            }
        });

        btnOcistiPolja.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnOcistiPolja.setText("Očisti polja");
        btnOcistiPolja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOcistiPoljaActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Popis proizvoda:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtNazivProizvoda, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtProizvodac, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtOpis, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCijena, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtKolicinaNaStanju, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnOcistiPolja, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnObrisi, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(btnDodaj, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnPromjeni, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 127, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNazivProizvoda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtProizvodac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addGap(8, 8, 8)
                        .addComponent(txtOpis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCijena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtKolicinaNaStanju, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnOcistiPolja)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnDodaj)
                            .addComponent(btnPromjeni)
                            .addComponent(btnObrisi)))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lstProizvodiValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstProizvodiValueChanged
        
        if (evt.getValueIsAdjusting()) {
            return;
        }
       
        if (lstProizvodi.getSelectedValue() == null) {
            pocisti();
            lstProizvodi.clearSelection();
            return;
        }
        
        obrada.setEntitet(lstProizvodi.getSelectedValue());

        txtNazivProizvoda.setText(obrada.getEntitet().getNaziv());
        
        if (obrada.getEntitet().getProizvodac() != null) {
            txtProizvodac.setText(obrada.getEntitet().getProizvodac().toString());
        } else {
            txtProizvodac.setText("");
        }
        
        if (obrada.getEntitet().getProizvodac() != null) {
            txtOpis.setText(obrada.getEntitet().getOpis().toString());
        } else {
            txtOpis.setText("");
        }
        
        try {
            txtCijena.setText(obrada.getEntitet().getCijena().toString());
        } catch (Exception e) {
            txtCijena.setText("");
        }
        
        try {
            txtKolicinaNaStanju.setText(obrada.getEntitet().getKolicinaNaStanju().toString());
        } catch (Exception e) {
            txtKolicinaNaStanju.setText("");
        }

    }//GEN-LAST:event_lstProizvodiValueChanged

    private void btnDodajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodajActionPerformed
        
        obrada.setEntitet(new Proizvod());
        postaviVrijednostiNaEntitet();
        
        try {
            obrada.create();
            pocisti();
            ucitaj(); 
        } catch (ZavrsniRadException ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getPoruka());
        }
    }//GEN-LAST:event_btnDodajActionPerformed

    private void btnPromjeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPromjeniActionPerformed
        
        if (obrada.getEntitet() == null || obrada.getEntitet().getSifra() == null) {
            JOptionPane.showMessageDialog(rootPane, "Prvo odaberite stavku");
            return;
        }
        
        postaviVrijednostiNaEntitet();

        try {
            obrada.update();
            pocisti();
            ucitaj();
        } catch (ZavrsniRadException e) {
            JOptionPane.showMessageDialog(rootPane, e.getPoruka());
        }
    }//GEN-LAST:event_btnPromjeniActionPerformed

    private void btnObrisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObrisiActionPerformed
        
        if (obrada.getEntitet() == null || obrada.getEntitet().getSifra() == null) {
            JOptionPane.showMessageDialog(rootPane, "Prvo odaberite stavku");
            return;
        }

        try {
            obrada.delete();
            pocisti();
            ucitaj();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Stavka se nalazi na računu - nemoguće obrisat!");
        }
    }//GEN-LAST:event_btnObrisiActionPerformed

    private void btnOcistiPoljaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOcistiPoljaActionPerformed
        pocisti();
    }//GEN-LAST:event_btnOcistiPoljaActionPerformed

    private void txtNazivProizvodaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNazivProizvodaKeyReleased
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
           txtProizvodac.requestFocus();
        }
    }//GEN-LAST:event_txtNazivProizvodaKeyReleased

    private void txtProizvodacKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtProizvodacKeyReleased
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
           txtOpis.requestFocus();
        }
    }//GEN-LAST:event_txtProizvodacKeyReleased

    private void txtOpisKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtOpisKeyReleased
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
           txtCijena.requestFocus();
        }
    }//GEN-LAST:event_txtOpisKeyReleased

    private void txtCijenaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCijenaKeyReleased
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
           txtKolicinaNaStanju.requestFocus();
        }
    }//GEN-LAST:event_txtCijenaKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDodaj;
    private javax.swing.JButton btnObrisi;
    private javax.swing.JButton btnOcistiPolja;
    private javax.swing.JButton btnPromjeni;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<Proizvod> lstProizvodi;
    private javax.swing.JTextField txtCijena;
    private javax.swing.JTextField txtKolicinaNaStanju;
    private javax.swing.JTextField txtNazivProizvoda;
    private javax.swing.JTextField txtOpis;
    private javax.swing.JTextField txtProizvodac;
    // End of variables declaration//GEN-END:variables

    private void ucitaj() {
        
        DefaultListModel<Proizvod> m = new DefaultListModel<>();
        m.addAll(obrada.getPodaci());
        lstProizvodi.setModel(m);
        
    }

    private void postaviVrijednostiNaEntitet() {
        
        var entitet = obrada.getEntitet();
        
        entitet.setNaziv(txtNazivProizvoda.getText());
        
        try {
            entitet.setProizvodac(txtProizvodac.getText());
        } catch (Exception e) {
            entitet.setProizvodac("");
        }
        
        try {
            entitet.setOpis(txtOpis.getText());
        } catch (Exception e) {
            entitet.setOpis("");
        }

        try {
            entitet.setCijena(new BigDecimal(txtCijena.getText()));
        } catch (Exception e) {
            entitet.setCijena(BigDecimal.ZERO);
        }

        try {
            entitet.setKolicinaNaStanju(new BigDecimal(txtKolicinaNaStanju.getText()));
        } catch (Exception e) {
            entitet.setKolicinaNaStanju(BigDecimal.ZERO);
        }
        
    }

    private void pocisti() {
        
        txtNazivProizvoda.setText("");
        txtProizvodac.setText("");
        txtOpis.setText("");
        txtCijena.setText("");
        txtKolicinaNaStanju.setText("");
        
    }
}
