/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edunova.zavrsni.view;

import edunova.zavrsni.controller.ObradaDjelatnik;
import edunova.zavrsni.model.Djelatnik;
import edunova.zavrsni.util.ZavrsniRadException;
import java.awt.event.KeyEvent;
import java.util.Arrays;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import org.mindrot.jbcrypt.BCrypt;

/**
 *
 * @author Skec
 */

//TODO

public class PromjeniLozinkuDjelatnikaForma extends javax.swing.JFrame {

    private ObradaDjelatnik obrada;
    /**
     * Creates new form PromjeniLozinkuDjelatnikaForma
     */
    public PromjeniLozinkuDjelatnikaForma() {
        initComponents();
        obrada = new ObradaDjelatnik();
        setTitle(Aplikacija.NASLOV_APP + " | Djelatnik: " + Aplikacija.djelatnik.getIme());
        lblImeDjelatnika.setText(Aplikacija.djelatnik.getIme());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnPromjeniLozinku = new javax.swing.JButton();
        lblImeDjelatnika = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        pswNovaLozinka = new javax.swing.JPasswordField();
        pswNovaLozinkaPotvrda = new javax.swing.JPasswordField();
        pswStaraLozinka = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel2.setText("Ime djelatnika:");

        jLabel3.setText("Unesi staru lozinku:");

        jLabel4.setText("Unesi novu lozinku:");

        btnPromjeniLozinku.setText("Promjeni lozinku");
        btnPromjeniLozinku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPromjeniLozinkuActionPerformed(evt);
            }
        });

        jLabel5.setText("Potvrdi novu lozinku:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5)
                    .addComponent(btnPromjeniLozinku, javax.swing.GroupLayout.DEFAULT_SIZE, 383, Short.MAX_VALUE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblImeDjelatnika, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(pswNovaLozinka)
                    .addComponent(pswNovaLozinkaPotvrda)
                    .addComponent(pswStaraLozinka))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(lblImeDjelatnika, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pswStaraLozinka, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pswNovaLozinka, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pswNovaLozinkaPotvrda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnPromjeniLozinku)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnPromjeniLozinkuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPromjeniLozinkuActionPerformed
        
        postaviVrijednostiNaEntitet();

        try {
            obrada.update();
        } catch (ZavrsniRadException e) {
            JOptionPane.showMessageDialog(rootPane, e.getPoruka());
        }
        
        JOptionPane.showMessageDialog(rootPane, "Lozinka promjenjena!");
    }//GEN-LAST:event_btnPromjeniLozinkuActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPromjeniLozinku;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblImeDjelatnika;
    private javax.swing.JPasswordField pswNovaLozinka;
    private javax.swing.JPasswordField pswNovaLozinkaPotvrda;
    private javax.swing.JPasswordField pswStaraLozinka;
    // End of variables declaration//GEN-END:variables

    private void provjeri(){
        
        try{
            if(pswStaraLozinka.toString().isEmpty()){
                obradiGresku(pswStaraLozinka, "Obavezno stara lozinka!");
                return;
            }          

            if(pswNovaLozinka.toString().isEmpty()){
                obradiGresku(pswNovaLozinka, "Obavezno nova lozinka!");
                return;
            }
            
            if(pswNovaLozinkaPotvrda.toString().isEmpty()){
                obradiGresku(pswNovaLozinkaPotvrda, "Obavezno potvrda nove lozinke!");
                return;
            }
            
            if(!Arrays.equals(pswNovaLozinka.getPassword(), pswNovaLozinkaPotvrda.getPassword())){
                obradiGresku(pswNovaLozinka, "Nova lozinka se ne podudara!");
                return;
            }
            
            Djelatnik o = obrada.autoriziraj(Aplikacija.djelatnik.getIme(), pswStaraLozinka.getPassword());

            if(o == null){
                obradiGresku(pswStaraLozinka, "Ime i lozinka ne odgovaraju");
                return;
            } 

        }catch(Exception e){
            obradiGresku(pswStaraLozinka, "Krivi unos!");
        }
    }
    
    private void obradiGresku(JComponent komponenta, String poruka){
        komponenta.requestFocus();
        JOptionPane.showMessageDialog(rootPane, poruka);
    }
    
    private void postaviVrijednostiNaEntitet() {
        
        provjeri();
        
        char[] pass = pswNovaLozinka.getPassword();
        String s = new String(pass);
           
        try {
            Aplikacija.djelatnik.setSifraDjelatnika(BCrypt.hashpw(s, BCrypt.gensalt()));
        } catch (Exception e) {
            obradiGresku(pswNovaLozinka, "Greška - nova lozinka");
        } 
        
        obrada.setEntitet(Aplikacija.djelatnik);
        
        try {
            obrada.update();
        } catch (ZavrsniRadException e) {
            System.out.println(e.getMessage());
        }      
        
    }


}
