/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edunova.zavrsni.view;

import edunova.zavrsni.controller.ObradaDjelatnik;
import edunova.zavrsni.model.Djelatnik;
import edunova.zavrsni.util.ZavrsniRadException;
import java.awt.event.KeyEvent;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import org.mindrot.jbcrypt.BCrypt;

/**
 *
 * @author Skec
 */

//TODO

public class PromjeniLozinkuDjelatnikaForma extends javax.swing.JFrame {

    private ObradaDjelatnik obrada;
    /**
     * Creates new form PromjeniLozinkuDjelatnikaForma
     */
    public PromjeniLozinkuDjelatnikaForma() {
        initComponents();
        obrada = new ObradaDjelatnik();
        setTitle(Aplikacija.NASLOV_APP + " | Djelatnik: " + Aplikacija.djelatnik.getIme());
        lblImeDjelatnika.setText(Aplikacija.djelatnik.getIme());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtStaraLozinka = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtNovaLozinka = new javax.swing.JTextField();
        btnPromjeniLozinku = new javax.swing.JButton();
        lblImeDjelatnika = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtNovaLozinkaPotvrda = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel2.setText("Ime djelatnika:");

        jLabel3.setText("Unesi staru lozinku:");

        txtStaraLozinka.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtStaraLozinkaKeyReleased(evt);
            }
        });

        jLabel4.setText("Unesi novu lozinku:");

        txtNovaLozinka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNovaLozinkaActionPerformed(evt);
            }
        });

        btnPromjeniLozinku.setText("Promjeni lozinku");
        btnPromjeniLozinku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPromjeniLozinkuActionPerformed(evt);
            }
        });

        jLabel5.setText("Potvrdi novu lozinku:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnPromjeniLozinku, javax.swing.GroupLayout.DEFAULT_SIZE, 383, Short.MAX_VALUE)
                        .addComponent(txtNovaLozinka)
                        .addComponent(txtStaraLozinka)
                        .addComponent(jLabel3)
                        .addComponent(jLabel4)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lblImeDjelatnika, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(txtNovaLozinkaPotvrda)))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(lblImeDjelatnika, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtStaraLozinka, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNovaLozinka, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNovaLozinkaPotvrda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnPromjeniLozinku)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtStaraLozinkaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtStaraLozinkaKeyReleased
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            promjeniLozinku();
           txtStaraLozinka.requestFocus();
        }
    }//GEN-LAST:event_txtStaraLozinkaKeyReleased

    private void btnPromjeniLozinkuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPromjeniLozinkuActionPerformed
        
        postaviVrijednostiNaEntitet();

        try {
            obrada.update();
        } catch (ZavrsniRadException e) {
            JOptionPane.showMessageDialog(rootPane, e.getPoruka());
        }
    }//GEN-LAST:event_btnPromjeniLozinkuActionPerformed

    private void txtNovaLozinkaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNovaLozinkaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNovaLozinkaActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPromjeniLozinku;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblImeDjelatnika;
    private javax.swing.JTextField txtNovaLozinka;
    private javax.swing.JTextField txtNovaLozinkaPotvrda;
    private javax.swing.JTextField txtStaraLozinka;
    // End of variables declaration//GEN-END:variables

    private void promjeniLozinku(){
        try{
            if(txtStaraLozinka.getText().isEmpty()){
                obradiGresku(txtStaraLozinka, "Obavezno stara lozinka!");
                return;
            }          

            if(txtNovaLozinka.getText().isEmpty()){
                obradiGresku(txtNovaLozinka, "Obavezno nova lozinka!");
                return;
            }
            
            if(txtNovaLozinkaPotvrda.getText().isEmpty()){
                obradiGresku(txtNovaLozinkaPotvrda, "Obavezno potvrda nove lozinke!");
                return;
            }
            
            if(txtNovaLozinka.getText() != txtNovaLozinkaPotvrda.getText()){
                obradiGresku(txtNovaLozinka, "Nova lozinka se ne podudara!");
                return;
            }

            ObradaDjelatnik oo = new ObradaDjelatnik();
            Djelatnik o = oo.autoriziraj(Aplikacija.djelatnik.getIme(), txtStaraLozinka.getText().toCharArray());

            if(o==null){
                obradiGresku(txtStaraLozinka, "Ime i lozinka ne odgovaraju");
                return;
            } 

        }catch(Exception e){
            obradiGresku(txtStaraLozinka, "Krivi unos!");
        }
    }
    
    private void obradiGresku(JComponent komponenta, String poruka){
        komponenta.requestFocus();
        JOptionPane.showMessageDialog(rootPane, poruka);
    }
    
    private void postaviVrijednostiNaEntitet() {
        
        var entitet = obrada.getEntitet();
        
        try {
            entitet.setSifraDjelatnika(BCrypt.hashpw(txtNovaLozinka.getText(), BCrypt.gensalt()));
        } catch (Exception e) {
            obradiGresku(txtNovaLozinka, "Greška - nova lozinka");
        }        
        
    }


}
