/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edunova.zavrsni.view;

import edunova.zavrsni.controller.ObradaProizvod;
import edunova.zavrsni.controller.ObradaRacun;
import edunova.zavrsni.controller.ObradaStavka;
import edunova.zavrsni.model.Proizvod;
import edunova.zavrsni.model.Racun;
import edunova.zavrsni.model.Stavka;
import edunova.zavrsni.util.ZavrsniRadException;
import java.util.List;
import javax.swing.DefaultListModel;

/**
 *
 * @author Skec
 */
public class RacuniForma extends javax.swing.JFrame {
    
    private ObradaProizvod obradaProizvod;
    private ObradaStavka obradaStavka;
    private ObradaRacun obradaRacun;
    
    /**
     * Creates new form RacuniForma
     */
    public RacuniForma() {
        initComponents();
        obradaRacun = new ObradaRacun();
        setTitle(Aplikacija.NASLOV_APP + " | Djelatnik: " + Aplikacija.djelatnik.getIme());
        ucitajRacune();
        txtRabat.setEditable(false);
        txtUkupno.setEditable(false);
        txtKupac.setEditable(false);
        txtDjelatnik.setEditable(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        lstPopisRacuna = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstStavkeOdabranogRacuna = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtRabat = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtUkupno = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtKupac = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtDjelatnik = new javax.swing.JTextField();
        cbStorniran = new javax.swing.JCheckBox();
        jLabel8 = new javax.swing.JLabel();
        lblDatumKreiranja = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lblBrojRacuna = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setType(java.awt.Window.Type.UTILITY);

        lstPopisRacuna.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstPopisRacunaValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(lstPopisRacuna);

        jScrollPane2.setViewportView(lstStavkeOdabranogRacuna);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Popis računa:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Stavke odabranog računa: ");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Rabat:");

        txtRabat.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtRabat.setText(" ");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Ukupno:");

        txtUkupno.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("kn");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Kupac:");

        txtKupac.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Djelatnik:");

        txtDjelatnik.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        cbStorniran.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cbStorniran.setForeground(new java.awt.Color(255, 0, 0));
        cbStorniran.setText("Storniran");
        cbStorniran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbStorniranActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Datum kreiranja:");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Broj računa:");

        lblBrojRacuna.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("→");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblDatumKreiranja, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel9)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(lblBrojRacuna, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtRabat)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel6))
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtKupac, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                                    .addComponent(txtDjelatnik)))
                            .addComponent(cbStorniran)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtUkupno, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5)))
                        .addGap(0, 14, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblBrojRacuna, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel9))
                                    .addGap(29, 29, 29)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel8)
                                        .addComponent(lblDatumKreiranja, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel3)
                                        .addComponent(txtRabat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel6)
                                        .addComponent(txtDjelatnik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel7)
                                        .addComponent(txtKupac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel4)
                                        .addComponent(txtUkupno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel5))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(cbStorniran))
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(166, 166, 166))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(21, 21, 21))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cbStorniranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbStorniranActionPerformed
        
        if(cbStorniran.isSelected()){
            lstPopisRacuna.getSelectedValue().setStorniran(true);
        }
    }//GEN-LAST:event_cbStorniranActionPerformed

    private void lstPopisRacunaValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstPopisRacunaValueChanged
        ucitajProizvodeRacuna();
        prikaziCijenu();
        prikaziRabat();
        prikaziKupca();
        prikaziDjelatnika();
        postaviStorniran();
        postaviDatum();
        postaviBrojRacuna();
    }//GEN-LAST:event_lstPopisRacunaValueChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox cbStorniran;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblBrojRacuna;
    private javax.swing.JLabel lblDatumKreiranja;
    private javax.swing.JList<Racun> lstPopisRacuna;
    private javax.swing.JList<Stavka> lstStavkeOdabranogRacuna;
    private javax.swing.JTextField txtDjelatnik;
    private javax.swing.JTextField txtKupac;
    private javax.swing.JTextField txtRabat;
    private javax.swing.JTextField txtUkupno;
    // End of variables declaration//GEN-END:variables

    private void ucitajRacune() {
        
        DefaultListModel<Racun> m = new DefaultListModel<>();
        m.addAll(obradaRacun.getPodaci());
        lstPopisRacuna.setModel(m);
    }

    private void ucitajProizvodeRacuna() {
        
        List<Stavka> stavke = lstPopisRacuna.getSelectedValue().getStavke();
        DefaultListModel<Stavka> m = new DefaultListModel<>();
        m.addAll(stavke);
        lstStavkeOdabranogRacuna.setModel(m);  
    }

    private void prikaziCijenu() {
        
        List<Stavka> stavke = lstPopisRacuna.getSelectedValue().getStavke();
                
        double cj = 0;
        double cijenaProizvoda = 0;
        
        for(int i = 0; i < stavke.size(); i++){
            cijenaProizvoda = stavke.get(i).getKolicina().doubleValue() *  
                    stavke.get(i).getProizvod().getCijena().doubleValue();
            cj += cijenaProizvoda;
        }
        
        double rabat = lstPopisRacuna.getSelectedValue().getRabat().doubleValue();
        
        if(rabat != 0){
            rabat = 100 - rabat;
            rabat /= 100;
            cj *= rabat;
        }
        
        String uk = String.format("%.2f",cj);
        StringBuilder sb = new StringBuilder(uk);
        char[] ukChar = uk.toCharArray();
        int index = 0;
        
        for(int i = 0; i<ukChar.length; i++){
             char c = ukChar[i];             
             if(c == ','){
                 index = i;
             }           
        }      
        
        sb.setCharAt(index, '.');
        
        txtUkupno.setText(sb.toString());
    }

    private void prikaziRabat() {        
        String rabat = String.valueOf(lstPopisRacuna.getSelectedValue().getRabat().doubleValue());
        txtRabat.setText(rabat);        
   }    

    private void prikaziKupca() {
        
        String kupac = "";
        
        if(lstPopisRacuna.getSelectedValue().getKupac() != null){
            kupac = lstPopisRacuna.getSelectedValue().getKupac().toString();
            txtKupac.setText(kupac);
        }else{
            txtKupac.setText("[kupac nije odabran]");
        }
    }

    private void prikaziDjelatnika() {
        
        txtDjelatnik.setText(lstPopisRacuna.getSelectedValue().getDjelatnik().toString());
    }

    private void postaviStorniran() {
        
        if(lstPopisRacuna.getSelectedValue().isStorniran()){
            cbStorniran.setSelected(true);
        }else{
            cbStorniran.setSelected(false);
        }
    }

    private void postaviDatum() {
    
        lblDatumKreiranja.setText(lstPopisRacuna.getSelectedValue().getDatumKreiranja());
    }

    private void postaviBrojRacuna() {
        
        lblBrojRacuna.setText(lstPopisRacuna.getSelectedValue().getSifra().toString());
    }
}
