/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edunova.zavrsni.view;

import edunova.zavrsni.controller.ObradaProizvod;
import edunova.zavrsni.controller.ObradaRacun;
import edunova.zavrsni.controller.ObradaStavka;
import edunova.zavrsni.model.Proizvod;
import edunova.zavrsni.model.Racun;
import edunova.zavrsni.model.Stavka;
import edunova.zavrsni.util.ZavrsniRadException;
import java.util.List;
import javax.swing.DefaultListModel;

/**
 *
 * @author Skec
 */
public class RacuniForma extends javax.swing.JFrame {
    
    private ObradaProizvod obradaProizvod;
    private ObradaStavka obradaStavka;
    private ObradaRacun obradaRacun;
    
    /**
     * Creates new form RacuniForma
     */
    public RacuniForma() {
        initComponents();
        obradaRacun = new ObradaRacun();
        setTitle(Aplikacija.NASLOV_APP + " | Djelatnik: " + Aplikacija.djelatnik.getIme());
        ucitajRacune();
        txtRabat.setEditable(false);
        txtUkupno.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        lstPopisRacuna = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstStavkeOdabranogRacuna = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnPrikaziDetaljeRacuna = new javax.swing.JToggleButton();
        jLabel3 = new javax.swing.JLabel();
        txtRabat = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtUkupno = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jScrollPane1.setViewportView(lstPopisRacuna);

        jScrollPane2.setViewportView(lstStavkeOdabranogRacuna);

        jLabel1.setText("Popis računa:");

        jLabel2.setText("Stavke odabranog računa: ");

        btnPrikaziDetaljeRacuna.setText("Prikaži detalje računa");
        btnPrikaziDetaljeRacuna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrikaziDetaljeRacunaActionPerformed(evt);
            }
        });

        jLabel3.setText("Rabat:");

        txtRabat.setText(" ");

        jLabel4.setText("Ukupno:");

        jLabel5.setText("kn");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPrikaziDetaljeRacuna, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(101, 101, 101)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtRabat, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtUkupno)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnPrikaziDetaljeRacuna))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtRabat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtUkupno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))))
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPrikaziDetaljeRacunaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrikaziDetaljeRacunaActionPerformed
        ucitajProizvodeRacuna();
        prikaziCijenu();
        prikaziRabat();
    }//GEN-LAST:event_btnPrikaziDetaljeRacunaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnPrikaziDetaljeRacuna;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<Racun> lstPopisRacuna;
    private javax.swing.JList<Stavka> lstStavkeOdabranogRacuna;
    private javax.swing.JTextField txtRabat;
    private javax.swing.JTextField txtUkupno;
    // End of variables declaration//GEN-END:variables

    private void ucitajRacune() {
        
        DefaultListModel<Racun> m = new DefaultListModel<>();
        m.addAll(obradaRacun.getPodaci());
        lstPopisRacuna.setModel(m);
    }

    private void ucitajProizvodeRacuna() {
        
        List<Stavka> stavke = lstPopisRacuna.getSelectedValue().getStavke();
        DefaultListModel<Stavka> m = new DefaultListModel<>();
        m.addAll(stavke);
        lstStavkeOdabranogRacuna.setModel(m);  
    }

    private void prikaziCijenu() {
        
        List<Stavka> stavke = lstPopisRacuna.getSelectedValue().getStavke();
                
        double cj = 0;
        double cijenaProizvoda = 0;
        
        for(int i = 0; i < stavke.size(); i++){
            cijenaProizvoda = stavke.get(i).getKolicina().doubleValue() *  
                    stavke.get(i).getProizvod().getCijena().doubleValue();
            cj += cijenaProizvoda;
        }
        
        double rabat = lstPopisRacuna.getSelectedValue().getRabat().doubleValue();
        
        if(rabat != 0){
            rabat = 100 - rabat;
            rabat /= 100;
            cj *= rabat;
        }
        
        String uk = String.format("%.2f",cj);
        
        txtUkupno.setText(uk);
    }

    private void prikaziRabat() {        
        String rabat = String.valueOf(lstPopisRacuna.getSelectedValue().getRabat().doubleValue());
        txtRabat.setText(rabat);        
   }
}
