/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PrimeNumView;

import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author Skec
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        setTitle("Prime Number APP");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtEnterNumber = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtIsPrime = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 153));

        jLabel1.setText("Enter number to check is it prime!");

        txtEnterNumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtEnterNumberKeyReleased(evt);
            }
        });

        jLabel2.setText("Your number is");

        jButton1.setText("Check!");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtIsPrime, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtEnterNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addComponent(jButton1)))
                .addContainerGap(104, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtEnterNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtIsPrime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(77, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        if (txtEnterNumber == null) {
            JOptionPane.showMessageDialog(rootPane, "Enter a number!");
            return;
        }
        
        try {
            int num = Integer.parseInt(txtEnterNumber.getText().toString());
            
            if(isPrime(num)){
                txtIsPrime.setText("prime!");
            }else{
                txtIsPrime.setText("not prime!");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Check if natural number is entered!");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtEnterNumberKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEnterNumberKeyReleased
        
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
                if (txtEnterNumber == null) {
                JOptionPane.showMessageDialog(rootPane, "Enter a number!");
                return;
            }

            try {
                int num = Integer.parseInt(txtEnterNumber.getText().toString());

                if(isPrime(num)){
                    txtIsPrime.setText("prime!");
                }else{
                    txtIsPrime.setText("not prime!");
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(rootPane, "Check if natural number is entered!");
            }
        }
            
    }//GEN-LAST:event_txtEnterNumberKeyReleased



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txtEnterNumber;
    private javax.swing.JTextField txtIsPrime;
    // End of variables declaration//GEN-END:variables

    private boolean isPrime(int num) {
        
        boolean isPrime = true;
        
        if(num < 2){
            isPrime = false;
        }
        
        for(int i = 2; i <= Math.sqrt(num); i++){
            if(num % i == 0){
                isPrime = false;
            }
        }
        
        return isPrime;
    }
}
